### ISSUE TITLE
how exactly the video(Graphical) is working?

### ISSUE THREAD

**Issue by ksajan** [rockytriton/DSOS#1]
I was following https://jsandler18.github.io/tutorial/dev-env.html for working on making an OS from scratch. but I couldn't understand how you got this working and can't find anything on the readme.

**Comment by rockytriton** [comment]
Hi Sanjan, I can't remember where I pulled all this info from, several sources.  But you need to make sure you use the correct raspberry pi for this.  It has to be the PI 3 B+.  There's a lot of good info here:  https://github.com/s-matyukevich/raspberry-pi-os . but they dont' cover video.

**Comment by rockytriton** [comment]
@ksajan hey you may want to look at the latest code I have now, it has the video working.  There is the start of a shell that uses it as well, just plug in the hdmi cable and it should work on a 3 B+.
